// DocsConfig: the single declarative object that drives a deployment
// (ADR §4). Deliberately scoped to what's actually consumable right now —
// componentOverrides and plugins (from ADR's full example) depend on
// registries that don't exist yet (Milestones 17 and 20) and are left out
// until those exist. This is additive: adding fields later won't break
// configs written against this version.
//
// Validated at runtime with zod, not just typed at compile time — unlike our
// spec-parsing input (at least machine-generated by spec tooling), a
// DocsConfig is realistically hand-edited by a person, so malformed input is
// a real, expected case to guard against, not a hypothetical one.

import { z } from "zod";

export const brandingSchema = z.object({
  title: z.string().min(1),
  logoUrl: z.url().optional(),
  faviconUrl: z.url().optional(),
});

export const specSourceSchema = z.object({
  type: z.enum(["url", "file", "inline"]),
  value: z.string().min(1),
});

export const layoutSchema = z.object({
  sidebarPosition: z.enum(["left", "right"]),
  mode: z.enum(["two-pane", "single-page"]),
});

export const featuresSchema = z.object({
  search: z.boolean(),
  tryItOut: z.boolean(),
});

export const docsConfigSchema = z.object({
  branding: brandingSchema,
  specSource: specSourceSchema,
  layout: layoutSchema,
  features: featuresSchema,
});

export type Branding = z.infer<typeof brandingSchema>;
export type SpecSource = z.infer<typeof specSourceSchema>;
export type Layout = z.infer<typeof layoutSchema>;
export type Features = z.infer<typeof featuresSchema>;
export type DocsConfig = z.infer<typeof docsConfigSchema>;
