// Generates app/theme.generated.css from @docs-platform/theme.
//
// Why a generated file instead of hand-writing the @theme block: the values
// here must always match what packages/theme/src actually exports (and what
// its tests verify) — hand-copying them risks drift the moment a token
// changes. This script is the single point where our tested token package
// becomes the CSS Tailwind actually reads.
//
// Requires @docs-platform/theme to already be built (`pnpm run build` from
// the repo root) — this script does not build it itself, to avoid hiding
// build-order in yet another implicit place.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defaultTheme, tokensToTailwindTheme } from "@docs-platform/theme";

const vars = tokensToTailwindTheme(defaultTheme);
const lines = Object.entries(vars)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join("\n");

const css = `/* AUTO-GENERATED by scripts/generate-theme.mjs — do not edit directly.
   Edit packages/theme/src/tokens/*.ts instead, then re-run \`pnpm run build\`
   at the repo root followed by this script (or \`pnpm run dev\`/\`build\`,
   which already do both). */
@theme {
${lines}
}
`;

const outPath = fileURLToPath(new URL("../app/theme.generated.css", import.meta.url));
writeFileSync(outPath, css);
console.log(`Generated theme.generated.css with ${Object.keys(vars).length} variables.`);
